using System.Text.Json;
using FluentAssertions;

namespace ROTA.UnitTests.Content;

/// <summary>
/// The reforge loop, as shipped content: every set piece has a reforged twin, a recipe that makes
/// it, and parts that some raid actually drops; every quest gear pool pays every piece at one
/// rate. Generated by <c>tools/content/reforge_sets.py</c>; these pin the invariants the generator
/// promises, so a hand edit to any of the five files cannot quietly break the loop.
/// </summary>
public class ReforgeContentTests
{
    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "ROTA.slnx")))
            dir = dir.Parent;
        if (dir is null) throw new InvalidOperationException("Could not locate the repo root (ROTA.slnx).");
        return dir.FullName;
    }

    private static JsonDocument Content(string file) =>
        JsonDocument.Parse(File.ReadAllText(
            Path.Combine(FindRepoRoot(), "src", "ROTA.Api", "content", file)));

    private static string S(JsonElement e, string name) =>
        e.TryGetProperty(name, out var p) && p.ValueKind == JsonValueKind.String ? p.GetString() ?? "" : "";

    // Conscript is not reforgeable: nothing on the live server drops or sells it.
    private static readonly HashSet<string> ExcludedSets = new() { "set_conscript" };

    [Fact]
    public void Every_set_piece_has_a_reforged_twin_that_is_strictly_better_and_shares_its_art()
    {
        using var doc = Content("gear.json");
        var gear = doc.RootElement.EnumerateArray().ToDictionary(g => S(g, "id"));
        var missing = new List<string>();
        var checkedCount = 0;

        foreach (var (id, g) in gear)
        {
            var set = S(g, "setId");
            if (id.EndsWith("_reforged") || set.Length == 0 || set.EndsWith("_reforged") || ExcludedSets.Contains(set)) continue;
            checkedCount++;
            if (!gear.TryGetValue(id + "_reforged", out var r)) { missing.Add(id); continue; }

            S(r, "setId").Should().Be(set + "_reforged", $"{id}: the reforged pieces form a set of their own, one per slot");
            S(r, "slot").Should().Be(S(g, "slot"), $"{id}: the reforged piece fills the same slot");
            S(r, "rarity").Should().Be(S(g, "rarity"), $"{id}: the frame colour does not change");
            S(r, "iconPath").Should().Be(S(g, "iconPath"), $"{id}: same object, same picture");
            long baseTotal = g.GetProperty("bonusAttack").GetInt64() + g.GetProperty("bonusDefense").GetInt64();
            long reforgedTotal = r.GetProperty("bonusAttack").GetInt64() + r.GetProperty("bonusDefense").GetInt64();
            reforgedTotal.Should().BeGreaterThan(baseTotal, $"{id}: a reforge that is not an upgrade is a scam");
        }

        missing.Should().BeEmpty("every set piece outside Conscript must have a reforged twin");
        checkedCount.Should().Be(96, "twelve sets of eight");
    }

    [Fact]
    public void Every_reforged_piece_has_a_recipe_that_consumes_the_base_piece_and_only_raid_parts()
    {
        using var gearDoc = Content("gear.json");
        using var recipeDoc = Content("recipes.json");
        using var itemDoc = Content("items.json");
        var items = itemDoc.RootElement.EnumerateArray().ToDictionary(i => S(i, "id"));
        var recipesByOutput = recipeDoc.RootElement.EnumerateArray()
            .Where(r => S(r, "category") == "Reforge")
            .ToDictionary(r => S(r, "outputId"));

        foreach (var g in gearDoc.RootElement.EnumerateArray())
        {
            var id = S(g, "id");
            if (!id.EndsWith("_reforged")) continue;
            var baseId = id[..^"_reforged".Length];

            recipesByOutput.Should().ContainKey(id, $"{id} needs a Reforge recipe");
            var recipe = recipesByOutput[id];
            S(recipe, "outputKind").Should().Be("Gear");
            recipe.GetProperty("goldCost").GetInt64().Should().BePositive($"{id}: a reforge costs gold");

            var ingredients = recipe.GetProperty("ingredients").EnumerateArray().ToList();
            ingredients.Should().HaveCount(2, $"{id}: the base piece and one kind of part");
            ingredients.Should().ContainSingle(i => S(i, "kind") == "Gear" && S(i, "id") == baseId && i.GetProperty("quantity").GetInt32() == 1,
                $"{id}: the reforge consumes exactly one base piece");

            var part = ingredients.Single(i => S(i, "kind") == "Item");
            var partId = S(part, "id");
            items.Should().ContainKey(partId, $"{id}: its part must be a shipped item");
            var isMount = S(g, "slot") == "Mount";
            partId.Should().EndWith(isMount ? "_tack" : "_scrap",
                $"{id}: mounts reforge with tack, body pieces with scrap");
            part.GetProperty("quantity").GetInt32().Should().BePositive();
        }
    }

    [Fact]
    public void Every_part_drops_from_at_least_one_raid_and_tack_is_always_rarer_than_scrap()
    {
        using var itemDoc = Content("items.json");
        using var tableDoc = Content("loot_tables.json");
        var parts = itemDoc.RootElement.EnumerateArray()
            .Select(i => S(i, "id"))
            .Where(id => id.EndsWith("_scrap") || id.EndsWith("_tack"))
            .ToList();
        parts.Should().HaveCount(24, "twelve sets, a scrap and a tack each");

        // part id -> best full-ladder chance across raid tables, per difficulty, top rung only.
        var seen = new HashSet<string>();
        var topRungChance = new Dictionary<(string Table, string Diff, string Part), double>();
        foreach (var t in tableDoc.RootElement.EnumerateArray())
        {
            if (S(t, "type") != "Raid") continue;
            foreach (var diff in t.GetProperty("difficulties").EnumerateObject())
            {
                if (!diff.Value.TryGetProperty("thresholdRewards", out var rungs) || rungs.ValueKind != JsonValueKind.Array) continue;
                foreach (var rung in rungs.EnumerateArray())
                {
                    if (!rung.TryGetProperty("itemDrops", out var drops) || drops.ValueKind != JsonValueKind.Array) continue;
                    foreach (var d in drops.EnumerateArray())
                    {
                        var id = S(d, "itemId");
                        if (!parts.Contains(id)) continue;
                        seen.Add(id);
                        topRungChance[(S(t, "id"), diff.Name, id)] = d.GetProperty("chance").GetDouble();
                    }
                }
            }
        }

        parts.Except(seen).Should().BeEmpty("a part no raid drops makes its recipe impossible");

        foreach (var ((table, diff, part), chance) in topRungChance)
        {
            if (!part.EndsWith("_tack")) continue;
            var scrap = part[..^"_tack".Length] + "_scrap";
            topRungChance.Should().ContainKey((table, diff, scrap), $"{table}/{diff}: a raid that drops tack drops the scrap too");
            chance.Should().BeLessThan(topRungChance[(table, diff, scrap)],
                $"{table}/{diff}: the mount's part is the rarest thing a raid gives up");
        }
    }

    [Fact]
    public void Guild_raids_have_loot_tables_now()
    {
        using var raids = Content("guild_raids.json");
        using var tables = Content("loot_tables.json");
        var tableIds = tables.RootElement.EnumerateArray().Select(t => S(t, "id")).ToHashSet();

        foreach (var r in raids.RootElement.EnumerateArray())
        {
            var lt = S(r, "lootTableId");
            lt.Should().NotBeEmpty($"{S(r, "id")}: a guild raid that drops nothing is not worth a guild's stamina");
            tableIds.Should().Contain(lt, $"{S(r, "id")}: its loot table must exist");
        }
    }

    [Fact]
    public void Quest_zone_pools_pay_every_set_piece_at_one_rate_and_every_set_piece_has_a_pool()
    {
        using var gearDoc = Content("gear.json");
        using var tableDoc = Content("loot_tables.json");
        var gear = gearDoc.RootElement.EnumerateArray().ToDictionary(g => S(g, "id"));
        var dropped = new HashSet<string>();

        foreach (var t in tableDoc.RootElement.EnumerateArray())
        {
            var tid = S(t, "id");
            if (!tid.StartsWith("lt_zone_")) continue;
            foreach (var diff in t.GetProperty("difficulties").EnumerateObject())
            {
                if (!diff.Value.TryGetProperty("gearDrops", out var drops) || drops.ValueKind != JsonValueKind.Array) continue;
                var setRates = new HashSet<double>();
                foreach (var d in drops.EnumerateArray())
                {
                    var id = S(d, "gearDefinitionId");
                    dropped.Add(id);
                    var chance = d.GetProperty("chance").GetDouble();
                    if (S(gear[id], "setId").Length > 0)
                    {
                        setRates.Add(chance);
                        // 1-in-50 per click at Normal, x1.5 on Nightmare, x2 on a boss node: 0.06 is the ceiling.
                        chance.Should().BeLessThanOrEqualTo(0.06 + 1e-9,
                            $"{tid}/{diff.Name}/{id}: quest gear is a grind, by request");
                    }
                }
                setRates.Count.Should().BeLessThanOrEqualTo(1,
                    $"{tid}/{diff.Name}: every set piece in a pool drops at the same odds");
            }
        }

        var orphans = gear.Values
            .Where(g => S(g, "setId").Length > 0 && !ExcludedSets.Contains(S(g, "setId"))
                        && S(g, "setId") != "set_pano" && !S(g, "setId").EndsWith("_reforged"))
            .Select(g => S(g, "id"))
            .Where(id => !dropped.Contains(id))
            .ToList();
        orphans.Should().BeEmpty("a set piece with no quest pool can never be found (Pano drops from q001-q005 instead)");
    }
}
