namespace ROTA.Domain.Entities;

/// <summary>
/// A single-use access key that gates player registration during beta.
/// Keys are generated by admins and consumed atomically at registration time.
/// </summary>
public class BetaKey
{
    // Required by EF Core
    private BetaKey() { }

    /// <summary>
    /// Factory — creates a new unredeemed beta key.
    /// </summary>
    /// <param name="key">The formatted key string (e.g. ROTA-XXXX-XXXX-XXXX).</param>
    /// <param name="createdBy">PlayerId of the admin who generated the key, or null for system-generated keys.</param>
    public static BetaKey Create(string key, Guid? createdBy) => new BetaKey
    {
        Id = Guid.NewGuid(),
        Key = key,
        CreatedByPlayerId = createdBy,
        IsRedeemed = false,
        RedeemedByPlayerId = null,
        RedeemedAt = null,
        CreatedAt = DateTimeOffset.UtcNow,
        UpdatedAt = DateTimeOffset.UtcNow,
        IsDeleted = false,
    };

    /// <summary>Unique surrogate PK.</summary>
    public Guid Id { get; private set; }

    /// <summary>The key string; unique across all keys.</summary>
    public string Key { get; private set; } = string.Empty;

    /// <summary>PlayerId of the admin who generated this key; null for system-seeded keys.</summary>
    public Guid? CreatedByPlayerId { get; private set; }

    /// <summary>True once the key has been claimed by a player at registration.</summary>
    public bool IsRedeemed { get; private set; }

    /// <summary>PlayerId of the player who redeemed this key.</summary>
    public Guid? RedeemedByPlayerId { get; private set; }

    /// <summary>UTC timestamp of redemption.</summary>
    public DateTimeOffset? RedeemedAt { get; private set; }

    /// <summary>Row creation timestamp.</summary>
    public DateTimeOffset CreatedAt { get; private set; }

    /// <summary>Last modification timestamp.</summary>
    public DateTimeOffset UpdatedAt { get; private set; }

    /// <summary>Soft-delete flag — deleted keys are invisible to normal queries.</summary>
    public bool IsDeleted { get; private set; }

    /// <summary>
    /// Marks the key as redeemed by <paramref name="playerId"/>.
    /// Throws <see cref="InvalidOperationException"/> if the key is already redeemed.
    /// In production use <see cref="ROTA.Application.Interfaces.IBetaKeyRepository.TryRedeemAsync"/>
    /// instead, which enforces atomicity at the database level.
    /// </summary>
    public void Redeem(Guid playerId)
    {
        if (IsRedeemed)
            throw new InvalidOperationException($"Beta key '{Key}' has already been redeemed.");

        IsRedeemed = true;
        RedeemedByPlayerId = playerId;
        RedeemedAt = DateTimeOffset.UtcNow;
        UpdatedAt = DateTimeOffset.UtcNow;
    }
}
